//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTWEB2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SanPham()
        {
            this.ChiTietGioHang = new HashSet<ChiTietGioHang>();
        }
    
        public int SanPhamID { get; set; }
        public string TenSanPham { get; set; }
        public Nullable<double> GiaBan { get; set; }
        public Nullable<int> SoLuotXem { get; set; }
        public Nullable<int> SoLuotBan { get; set; }
        public Nullable<int> SoLuongTon { get; set; }
        public string MoTa { get; set; }
        public string XuatXu { get; set; }
        public Nullable<int> LoaiID { get; set; }
        public Nullable<int> NhaSanXuatID { get; set; }
        public Nullable<System.DateTime> NgayTiepNhan { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietGioHang> ChiTietGioHang { get; set; }
        public virtual Loai Loai { get; set; }
        public virtual NhaSanXuat NhaSanXuat { get; set; }
    }
}
